doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        mapping_types:
            enum: string
        types:
            product_id: App\Product\Infrastructure\Doctrine\ProductIdType
            user_id: App\User\Infrastructure\Doctrine\UserIdType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Product:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/mappings/Product'
                prefix: 'App\Product\Domain'
                alias: Product
            User:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/mappings/User'
                prefix: 'App\User\Domain'
                alias: User
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
