services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: skeleton_php
    volumes:
      - ./:/var/www/skeleton
    depends_on:
      - db
    networks:
      - skeleton-network

  db:
    image: postgres:16.6-bookworm
    container_name: skeleton_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: skeleton
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    ports:
        - ${APP_DATABASE_PORT:-5432}:5432
    networks:
      - skeleton-network

  nginx:
    image: nginx:alpine
    container_name: skeleton_nginx
    volumes:
      - ./:/var/www/skeleton
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.symfony.rule=Host(`skeleton.localhost`)"  # Remplacez par votre domaine
        - "traefik.http.services.symfony.loadbalancer.server.port=80"
    networks:
      - skeleton-network
    depends_on:
        -   php

  traefik:
      image: traefik:v2.10
      container_name: skeleton-traefik
      command:
          - "--api.insecure=true"
          - "--providers.docker=true"
          - "--entrypoints.web.address=:80"
      ports:
          - "80:80"
          - "8080:8080"
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
      networks:
          - skeleton-network

volumes:
  db_data:

networks:
    skeleton-network:
